compare_speed: true
trainer: LanguageModelTrainer
training:
  model_type: llama
  project_name: RAG_llama2-chat
  model_name_or_path: ../llama2-chat
  tokenizer_name_or_path: ../llama2-chat
  kg_model_name_or_path: RAG-best
  num_layers_unfrozen: -1
  gradient_checkpointing: true
  optimizer: 
    name: Lamb
    kwargs:
      lr: 1e-3
      weight_decay: 0.0
      betas: [0.9, 0.999]
      eps: 1e-08
  scheduler:
    name: LinearLR
    kwargs:
      total_iters: 10
  num_epochs: 100000
  log_with: tensorboard
  project_dir: output_sa_llama2/
  negatives_in_device: true
  negatives_x_device: true
  predict_from_last: 10000
  eval_step: 1000
  start_from: 0
  skip_steps: 0
  cross_attention_activation_function: silu
  add_cross_attention_layer_number: 31
  kb_path: ../data_of_ReGPT/En-Wiki/phrases_embeddings.npy
  freeze_retrieval_head: true
  freeze_lm_head: true
  metrics:
    - f1
    - accuracy
  target_metric: accuracy

dataset:
  number_of_docs: 20
  inference_with_explict_docs_for_test: true
  train:
    2WikiMultihopQA:
      data_name_or_path: ../data_of_ReGPT/QA_datasets_wTop50/2WikiMultihopQA/sorted_datasets_train/
      dataset_name: QADataset4Chat
      batch_size: 2
      num_epochs: 805
      max_seq_len: 8192
      knowledge_max_seq_len: 8192
      dynamic_sampler: false
      corpus: ../data_of_ReGPT/Wiki-corpus/train
      system_prompt: "You are a helpful assistant. Please answer user question to the best of your ability. The answer MUST in ONE OR FEW WORDS. The answer is within the question."
      max_tokens: 8192
    complex_web_questions:
      data_name_or_path: ../data_of_ReGPT/QA_datasets_wTop50/complex_web_questions/train/
      dataset_name: QADataset4Chat
      batch_size: 2
      num_epochs: 805
      max_seq_len: 8192
      knowledge_max_seq_len: 8192
      dynamic_sampler: false
      corpus: ../data_of_ReGPT/Wiki-corpus/train
      system_prompt: "You are a helpful assistant. Please answer user question to the best of your ability. The answer MUST in ONE OR FEW WORDS."
      max_tokens: 8192
  test:
    2WikiMultihopQA:
      dataset_name: QADataset4ChatTest
      batch_size: 1
      data_name_or_path:  ../data_of_ReGPT/QA_datasets_wTop50/2WikiMultihopQA/sorted_datasets_dev/
      max_seq_len: 8192
      knowledge_max_seq_len: 8192
      max_new_tokens: 8
      index_path: ../data_of_ReGPT/Wiki-corpus/bm25_index/
      corpus: ../data_of_ReGPT/Wiki-corpus/train/
      system_prompt: "You are a helpful assistant. Please answer user question to the best of your ability. The answer MUST in ONE OR FEW WORDS. The answer is within the question."
      dynamic_sampler: false
    complex_web_questions:
      dataset_name: QADataset4ChatTest
      batch_size: 1
      data_name_or_path:  ../data_of_ReGPT/QA_datasets_wTop50/complex_web_questions/validation/
      max_seq_len: 8192
      knowledge_max_seq_len: 8192
      max_new_tokens: 8
      index_path: ../data_of_ReGPT/Wiki-corpus/bm25_index/
      corpus: ../data_of_ReGPT/Wiki-corpus/train/
      system_prompt: "You are a helpful assistant. Please answer user question to the best of your ability. The answer MUST in ONE OR FEW WORDS."
      dynamic_sampler: false

generation_kwargs:
  min_length: 0
  max_length: 512
  do_sample: true
  top_k: 5
  top_p: 0.95

RAG_kwargs:
  faiss:
    dimension: 768
  retrieval_step: 10
  topk: 6