trainer: LanguageModelTrainer
training:
  model_type: llama
  project_name: RAG_llama3-chat-sa-rag
  model_name_or_path: ../llama3-chat
  tokenizer_name_or_path: ../llama3-chat
  project_dir: output_sft/
  kg_model_name_or_path: RAG-best
  num_layers_unfrozen: -1
  gradient_checkpointing: true
  optimizer: 
    name: Lamb
    kwargs:
      lr: 1e-3
      weight_decay: 0.0
      betas: [0.9, 0.999]
      eps: 1e-08
  scheduler:
    name: LinearLR
    kwargs:
      total_iters: 10
  num_epochs: 100000
  log_with: tensorboard
  negatives_in_device: true
  negatives_x_device: true
  predict_from_last: 10000
  eval_step: 4000
  start_from: 0
  skip_steps: 0
  cross_attention_activation_function: silu
  add_cross_attention_layer_number: 31
  kb_path: ../data_of_ReGPT/En-Wiki/phrases_embeddings.npy
  freeze_retrieval_head: true
  freeze_lm_head: true
  metrics:
    - f1
    - accuracy
  target_metric: accuracy

dataset:
  number_of_docs: 20
  inference_with_explict_docs_for_test: true
  train:
    hotpotqa:
      data_name_or_path: ../data_of_ReGPT/QA_datasets_wTop50/hotpotqa/sorted_datasets_train/
      dataset_name: QADataset4Chat
      batch_size: 4
      num_epochs: 805
      max_seq_len: 8192
      dynamic_sampler: false
      corpus: ../data_of_ReGPT/Wiki-corpus/train
      max_tokens: 4096
    complex_web_questions:
      data_name_or_path: ../data_of_ReGPT/QA_datasets_wTop50/complex_web_questions/train/
      dataset_name: QADataset4Chat
      batch_size: 4
      num_epochs: 805
      max_seq_len: 8192
      dynamic_sampler: false
      corpus: ../data_of_ReGPT/Wiki-corpus/train
      max_tokens: 4096
    metaqa:
      data_name_or_path: ../data_of_ReGPT/QA_datasets_wTop50/metaqa/train/
      dataset_name: QADataset4Chat
      batch_size: 4
      num_epochs: 805
      max_seq_len: 8192
      dynamic_sampler: false
      corpus: ../data_of_ReGPT/Wiki-corpus/train
      max_tokens: 4096
  test:
    hotpotqa:
      dataset_name: QADataset4ChatTest
      batch_size: 4
      data_name_or_path:  ../data_of_ReGPT/QA_datasets_wTop50/hotpotqa/sorted_datasets_validation/
      max_seq_len: 8192
      max_new_tokens: 32
      index_path: ../data_of_ReGPT/Wiki-corpus/bm25_index/
      corpus: ../data_of_ReGPT/Wiki-corpus/train/
      dynamic_sampler: false
    complex_web_questions:
      dataset_name: QADataset4ChatTest
      batch_size: 4
      data_name_or_path:  ../data_of_ReGPT/QA_datasets_wTop50/complex_web_questions/validation/
      max_seq_len: 8192
      max_new_tokens: 32
      index_path: ../data_of_ReGPT/Wiki-corpus/bm25_index/
      corpus: ../data_of_ReGPT/Wiki-corpus/train/
      dynamic_sampler: false
    metaqa:
      dataset_name: QADataset4ChatTest
      batch_size: 4
      data_name_or_path:  ../data_of_ReGPT/QA_datasets_wTop50/metaqa/test/
      max_seq_len: 8192
      max_new_tokens: 32
      index_path: ../data_of_ReGPT/Wiki-corpus/bm25_index/
      corpus: ../data_of_ReGPT/Wiki-corpus/train/
      dynamic_sampler: false

generation_kwargs:
  min_length: 0
  max_length: 512
  do_sample: true
  top_k: 5
  top_p: 0.95

RAG_kwargs:
  faiss:
    dimension: 768
  retrieval_step: 10
  topk: 6
