trainer: ReGPTLanguageModelTrainer
training:
  project_name: ReGPT-sft
  model_name_or_path: gpt2
  tokenizer_name_or_path: ../llama2-7b-phrase-tokenizer-trained-on-WikiText103/
  num_layers_unfrozen: -1
  gradient_checkpointing: true
  optimizer: 
    name: Lamb
    kwargs:
      lr: 1e-3
      weight_decay: 0.0
      betas: [0.9, 0.999]
      eps: 1e-08
  scheduler:
    name: LinearLR
    kwargs:
      start_factor: 0.9
      total_iters: 50
  num_epochs: 1000
  log_with: tensorboard
  project_dir: output/

dataset:
  batch_size: 128
  train:
    data_name_or_path: Dahoas/rm-static
    max_seq_len: 128
    train_or_test: train
    negative_depth: 1
  test:
    data_name_or_path: Dahoas/rm-static
    max_seq_len: 128
    train_or_test: test
    negative_depth: 1

generation_kwargs:
  min_length: 0
  max_length: 512
  do_sample: false
  top_k: 1
  top_p: 1.0
  num_return_sequences: 1

ReGPT_kwargs:
  faiss:
    index_type: Flat
    dimension: 4096
    nprobe: 10000
    phrases_path: ../phrases_WikiText-103/phrases_WikiText-103.npy
    matrix_path: ../phrases_WikiText-103/phrases_embeddings_WikiText103_normalized.npy
  negative_path: ../phrases_WikiText-103/phrases_embeddings_WikiText103_negatives.tsv
  negative_depth_in_pool: 101
  FNTP_threshold: 10
