batch_size: 256
dev_batch_size: 256
q_max_seq_len: 512
p_max_seq_len: 512
retriever_model_name_or_path: ../data/RetroMAE_MSMARCO_distill/
model_out_dir: output/
learning_rate: 1e-5
report: 10
num_epochs: 1000
qrels: ''
# collection: ../En-Wiki/corpus.tsv
# collection: ../data_of_ReGPT/
query: ''
gradient_checkpoint: true
negatives_x_device: false
negatives_in_device: false
use_faiss: false
project_dir: output/
project_name: dense_retrieval_pretrain_with_query_generation
dataset_class_name: CorpusPretrainDatasetByQueryGeneration
warm_start_from: ''
top_k: 50
corpus_embeddings: ../data_of_ReGPT/Wiki-corpus/phrases_embeddings.npy
dev_querys: 
  - ../data_of_ReGPT/new_qa_datasets/MuSiQue/train
  - ../data_of_ReGPT/new_qa_datasets/MuSiQue/validation
  - ../data_of_ReGPT/new_qa_datasets/complex_web_questions/train
  - ../data_of_ReGPT/new_qa_datasets/complex_web_questions/validation
  - ../data_of_ReGPT/new_qa_datasets/metaqa/train
  - ../data_of_ReGPT/new_qa_datasets/metaqa/test
  # - ../data_of_ReGPT/QA_datasets_wTop10/msmarco_qa/sorted_datasets_train/
  # - ../data_of_ReGPT/QA_datasets_wTop10/msmarco_qa/sorted_datasets_test/
  # - ../data_of_ReGPT/QA_datasets_wTop10/eli5/sorted_datasets_train
  # - ../data_of_ReGPT/QA_datasets_wTop10/eli5/sorted_datasets_test
  # - ../data_of_ReGPT/QA_datasets_wTop10/hotpotqa/sorted_datasets_train
  # - ../data_of_ReGPT/QA_datasets_wTop10/hotpotqa/sorted_datasets_validation
  # - ../data_of_ReGPT/QA_datasets_woEmb/2WikiMultihopQA/sorted_datasets_train/
  # - ../data_of_ReGPT/QA_datasets_woEmb/2WikiMultihopQA/sorted_datasets_dev/
  # - ../data_of_ReGPT/QA_datasets_woEmb/nq/sorted_datasets_train/
  # - ../data_of_ReGPT/QA_datasets_woEmb/nq/sorted_datasets_test/
corpus_names: 
  - MuSiQue-train
  - MuSiQue-validation
  - complex_web_questions-train
  - complex_web_questions-validation
  - metaqa-train
  - metaqa-test
  # - msmarco_qa-train
  # - msmarco_qa-test
  # - eli5-train
  # - eli5-test
  # - hotpotqa-train
  # - hotpotqa-validation
  # - 2WikiMultihopQA-train
  # - 2WikiMultihopQA-dev
  # - nq-train
  # - nq-test

