batch_size: 256
dev_batch_size: 256
q_max_seq_len: 512
p_max_seq_len: 512
retriever_model_name_or_path: ../data/RetroMAE_MSMARCO_distill/
model_out_dir: output/
learning_rate: 1e-5
report: 10
num_epochs: 1000
qrels: ''
# collection: ../En-Wiki/corpus.tsv
# collection: ../data_of_ReGPT/
corpus_embeddings: ../data_of_ReGPT/En-Wiki/phrases_embeddings.npy
query: ''
dev_query: ../data_of_ReGPT/En-Wiki/sorted_datasets_test
gradient_checkpoint: true
negatives_x_device: true
negatives_in_device: true
use_faiss: false
project_dir: output/
project_name: dense_retrieval_pretrain_with_query_generation
dataset_class_name: CorpusPretrainDatasetByQueryGeneration
corpus_name: wiki
warm_start_from: ''
top_k: 10
