batch_size: 256
dev_batch_size: 256
q_max_seq_len: 512
p_max_seq_len: 512
retriever_model_name_or_path: ../data/RetroMAE_MSMARCO_distill/
model_out_dir: output/
learning_rate: 1e-5
report: 10
num_epochs: 1000
qrels: ''
# collection: ../En-Wiki/corpus.tsv
# collection: ../data_of_ReGPT/
query: ''
gradient_checkpoint: true
negatives_x_device: false
negatives_in_device: false
use_faiss: false
project_dir: output/
project_name: dense_retrieval_pretrain_with_query_generation
dataset_class_name: CorpusPretrainDatasetByQueryGeneration
warm_start_from: ''
top_k: 10
corpus_embeddings: ../data_of_ReGPT/Wiki-corpus/phrases_embeddings.npy
dev_query: ../data_of_ReGPT/QA_datasets/nq/train
corpus_name: nq-train
