### model
model_name_or_path: ../llama3-chat/

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: hotpotAnd2wikihop
template: llama3
cutoff_len: 1024
max_samples: 257901
overwrite_cache: false
preprocessing_num_workers: 16

### output
output_dir: ../output/saves/llama3-8b-chat/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 64
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 64
eval_strategy: steps
eval_steps: 20
